# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 733fe7f302370085b510ada2953872fe885debe34b82bc5ac25822984b8a2213e67e3f0e8f2c0740c6cf8b4369bc06453a7d213d71cce164a56a5ebe11464b7f

test:
  secret_key_base: 45971091c3a80785443ba5423b8a34e11261cc450ac89e415a6aea669e697cb033b8c0e605b871c156a617e8015500afe6e2ae83cb49c5645019c32200c8b8c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
